### ISSUE TITLE
Add support for Wifi

### ISSUE THREAD

**Issue by brunoleon** [hacf-fr/sfrbox-api#117]
Hello,

first thanks for your work providing this API.

I would like to add support for wifi clients listing so that we can use it for presence detection in HA.
I started working on it before reading that you advice on creating an issue before coding.

Specifically, current code is looking for "namespace" in response but the method `wlan.getClientList` does not have "wlan" namespace in the response.

Do you have any preference on how I should handle this ?

Thanks

**Comment by epenet** [comment]
I'm sorry it seems that I didn't see this message.
I don't have any preference right now, but feel free to create a PR and we can review that.
